server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attributeservice?createDatabaseIfNotExist=true
    username: root  
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true       
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: attribute-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

application:
  config:
    product-url: http://localhost:8082
jwt:
  secret: mQz7qDcLZxpDCVh/2zyoxs6my1LOkppq7x/+SkOsO78j6U3MOlt06o4h5G3gH+M8QuneFwaMtlXT12L61n1lTg==
