server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productserverdb?createDatabaseIfNotExist=true
    username: root  
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true       
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: product-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# application:
#   config:
#     inventory-url: http://localhost:8080/api/v1/inventories
