server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userserverdb?createDatabaseIfNotExist=true
    username: root  
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true       
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: user-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenminhco2964@gmail.com
    password: znqzohaqvognuaff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
